# Generated by Django 3.0.4 on 2020-05-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='parentcomment',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='postcomment',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='addedTime',
            new_name='timeStamp',
        ),
    ]
